# Generated by Django 3.2.11 on 2022-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='university.Subject'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(default='2022-01-20'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hired_date',
            field=models.DateField(default='2022-01-20'),
        ),
    ]
