# Generated by Django 3.2.11 on 2022-01-22 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20220121_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hired_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hired_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
