# Generated by Django 3.2.11 on 2022-01-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20220119_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hired_date',
            field=models.DateField(default='2022-01-19'),
        ),
    ]
