# Generated by Django 3.2.11 on 2022-01-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(default=13770000, max_length=20),
            preserve_default=False,
        ),
    ]
