# Generated by Django 3.2.11 on 2022-01-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
